apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-draft
  labels:
    app: go-draft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-draft
  template:
    metadata:
      labels:
        app: go-draft
    spec:
      containers:
        - name: go-draft
          image: go-draft:latest
          ports:
            - containerPort: 80